version: "3"
services:
    jenkins:
      image: 'jenkins/jenkins:latest'
      container_name: 'jenkins'      
    #   ports:
    #     - '50000:50000'
        # - '8100:8080'        
    #   expose:
    #     - '8080'
    #     - '50000'
      volumes:
        - './jenkins_home:/var/jenkins_home'
      environment:
        TZ: "Asia/Seoul"
      restart: always


    nginx-proxy:
      image: nginx:latest
      container_name: nginx-proxy
      volumes:
        - ../../config/sites-available/test.devspoon_ng.conf:/etc/nginx/sites-available/test.devspoon_ng.conf          
        - ../../config/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
        - ../../config/fastcgi/fastcgi_params:/etc/nginx/fastcgi_params
        - ../../nginx_cache/:/etc/nginx/cache/
        - ../../ssl:/etc/nginx/ssl/
        - ../../log/nginx/:/log/nginx/
      ports:
        - "80:80"
        - "443:443"
      environment:
        TZ: "Asia/Seoul"
      restart: always
      depends_on:
        - jenkins