version: "3"
services:
  webserver:
    image: nginx:latest
    working_dir: /application
    container_name: nginx-php-webserver      
    volumes:
        - ../../www:/www
        - ../../config/conf.d/:/etc/nginx/conf.d/
        - ../../config/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
        - ../../log:/log
    ports:
        - "80:80"
    restart: always


  app:
    build: ../../docker/php-fpm/
    working_dir: /application
    container_name: php-fpm7.3      
    volumes:
        - ../../www:/www
        - ../../config/pool.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
        - ../../config/php_ini/php.ini:/usr/local/etc/php/php.ini
    restart: always